PLATFORMS = [
    {
        "name": "GitHub",
        "profile_url_template": "https://github.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Reddit",
        "profile_url_template": "https://www.reddit.com/user/{username}",
        "check_url_template": "https://www.reddit.com/user/{username}/about.json",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "headers": {
            "User-Agent": "Mozilla/5.0 (compatible; HandleScout/1.0; +https://example.com)",
        },
    },
    {
        "name": "TikTok",
        "profile_url_template": "https://www.tiktok.com/@{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "unknown_markers": [
            "verify you are human",
            "captcha",
            "unusual traffic",
            "something went wrong",
        ],
        "available_markers": [
            "couldn't find this account",
            "couldn't find this user",
            "user not found",
        ],
        "taken_markers": ["\"uniqueId\":\"{username}\""],
        "ambiguous_on_200": True,
        "headers": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
            "Accept-Language": "en-US,en;q=0.9",
        },
    },
    {
        "name": "X",
        "profile_url_template": "https://x.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
        "unknown_markers": [
            "something went wrong",
            "unusual activity",
            "retry",
            "access denied",
        ],
        "available_markers": [
            "this account doesn't exist",
            "account doesn’t exist",
        ],
        "ambiguous_on_200": True,
        "headers": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
            "Accept-Language": "en-US,en;q=0.9",
        },
    },
    {
        "name": "GitLab",
        "profile_url_template": "https://gitlab.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Bitbucket",
        "profile_url_template": "https://bitbucket.org/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Dev.to",
        "profile_url_template": "https://dev.to/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "CodePen",
        "profile_url_template": "https://codepen.io/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Dribbble",
        "profile_url_template": "https://dribbble.com/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
    {
        "name": "Behance",
        "profile_url_template": "https://www.behance.net/{username}",
        "check_method": "GET",
        "available_statuses": [404],
        "taken_statuses": [200],
        "unknown_statuses": [429, 403, 401],
    },
]
